<?php
return [
    [
        'id' => 1,
        'user_type' => 1,
        'name' => 'Admin',
        'username' => 'admin',
        'email' => 'admin@gmail.com',
        'auth_key' => 'UXaIx3_T8US8fVJg7YhgZ6XfhCWzCdex',
        // 'password' => '123456',
        'password_hash' => '$2y$13$4ePxPCsPvNSxBkPKhBh87O4dfHGXtOEibM9ZptsiWq2Q7Kci073bC',
        'password_reset_token' => '',
        'status' => 10,
        'created_at' => '1484005922',
        'updated_at' => '1484005922',
        'birthday' => '1996-07-28',
        'gender' => 'M',
        'profile_picture' => 'assets/pages/img/avatars/default-avatar.png',
    ],
    [
        'id' => 2,
        'user_type' => 3,
        'name' => 'Testing PT',
        'username' => 'testing_pt',
        'email' => 'testing_pt@gmail.com',
        'auth_key' => 'saIx3_T8Udfssg7YhgZ6XshCWzCdd',
        // 'password' => '123456',
        'password_hash' => '$2y$13$4ePxPCsPvNSxBkPKhBh87O4dfHGXtOEibM9ZptsiWq2Q7Kci073bC',
        'password_reset_token' => '',
        'status' => 10,
        'created_at' => '1484005922',
        'updated_at' => '1484005922',
        'birthday' => '1996-12-20',
        'gender' => 'M',
        'profile_picture' => 'assets/pages/img/avatars/default-avatar.png',
    ],
    [
        'id' => 3,
        'user_type' => 4,
        'name' => 'Testing Cliente',
        'username' => 'testing_cliente',
        'email' => 'testing_cliente@gmail.com',
        'auth_key' => 'UXaIx3_sdsdfYhgZ6XfhCWzCdex',
        // 'password' => '123456',
        'password_hash' => '$2y$13$4ePxPCsPvNSxBkPKhBh87O4dfHGXtOEibM9ZptsiWq2Q7Kci073bC',
        'password_reset_token' => '',
        'status' => 10,
        'created_at' => '1484005922',
        'updated_at' => '1484005922',
        'birthday' => '1996-12-20',
        'gender' => 'M',
        'profile_picture' => 'assets/pages/img/avatars/default-avatar.png',
    ],
];
