<?php
return [
    'inactive-user' => [
        'id' => 4,
        'user_type' => 3,
        'name' => 'Inactive User',
        'username' => 'testing_inactive_user',
        'email' => 'testing_inactive_user@gmail.com',
        'auth_key' => 'UXaIx3_T8sssdVJg7YhgZ6XfhCWzCdex',
        // 'password' => '123456',
        'password_hash' => '$2y$13$4ePxPCsPvNSxBkPKhBh87O4dfHGXtOEibM9ZptsiWq2Q7Kci073bC',
        'password_reset_token' => '',
        'status' => 0,
        'created_at' => '1484005922',
        'updated_at' => '1484005922',
        'birthday' => '1983-02-10',
        'gender' => 'M',
        'profile_picture' => 'assets/pages/img/avatars/default-avatar.png',
    ],
    'reset-password-user' => [
        'id' => 5,
        'user_type' => 1,
        'name' => 'Okirlin',
        'username' => 'okirlin',
        'email' => 'brady.renner@rutherford.com',
        'auth_key' => 'iwTNae9t34OmnK6l4vT4IeaTk-YWI2Rv',
        // 'password' => 'password_0',
        'password_hash' => '$2y$13$CXT0Rkle1EMJ/c1l5bylL.EylfmQ39O5JlHJVFpNn618OUS1HwaIi',
        'password_reset_token' => 't5GU9NwpuGYSfb7FEZMAxqtuz2PkEvv_' . time(),
        'status' => 10,
        'created_at' => '1391885313',
        'updated_at' => '1391885313',
        'birthday' => '1991-05-18',
        'gender' => 'M',
        'profile_picture' => 'assets/pages/img/avatars/default-avatar.png',
    ],
];
